version: '2'

services:

  wordpress:
    image: wordpress:4.6.1-apache
    ports:
      - 8080:80
    volumes:
      - ./wp-content:/var/www/html/wp-content
    links:
      - mysql
    environment:
      WORDPRESS_DB_PASSWORD: secretls

  mysql:
    image: mariadb:10.1.18
    ports:
        - 3306:3306
    volumes:
        - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret